version: 2.0

jobs:
  build-and-test:
    context: server2x-testing
    docker:
      - image: circleci/python:3.9.0
        auth:
          username: jtreutel
          password: $DOCKERHUB_PW
    steps:
      - checkout
      - run: 
          name: Installing requirements
          command: |
            pip3 install -r requirements.txt
      - run: 
          name: Install Chrome 86 and Chromedriver 86
          command: |
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt install ./google-chrome-stable_current_amd64.deb
            wget https://chromedriver.storage.googleapis.com/86.0.4240.22/chromedriver_linux64.zip
            unzip ./chromedriver_linux64.zip
            sudo mv chromedriver /usr/local/bin/
      - run:
          name: Test website
          command: | 
            nohup python src/site.py > site.log 2>&1 &
            python -m pytest
  build-image-and-push:
    context: server2x-testing
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - setup_remote_docker:
      - run:
          name: Build and push Docker image to ECR
          command: |
            docker build -f Dockerfile -t simpleflasksite:$CIRCLE_BUILD_NUM . 
            AWS_ACCT_NO=$(aws sts get-caller-identity --region $AWS_REGION | jq -r '.Account')
            docker login -u AWS -p $(aws ecr get-login-password --region $AWS_REGION) $AWS_ACCT_NO.dkr.ecr.$AWS_REGION.amazonaws.com
            docker push "$AWS_ACCT_NO.dkr.ecr.$AWS_REGION.amazonaws.com/simpleflasksite:$CIRCLE_BUILD_NUM"
          

workflows:
  version: 2
  main:
    jobs:
      - build-and-test
      - build-image-and-push
      #- aws-ecr/build-and-push-image:
      #    repo: "${AWS_RESOURCE_NAME_PREFIX}"
      #    tag: "${CIRCLE_SHA1}"
      #- aws-ecs/deploy-service-update:
      #    requires:
      #      - aws-ecr/build-and-push-image # only run this job once aws-ecr/build-and-push-image has completed
      #    family: "${AWS_RESOURCE_NAME_PREFIX}-service"
      #    cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
      #    container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_SHA1}"